version: "3.8"
services:
  app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - UI_PORT=5001
      - CLAUDE_MODEL=${CLAUDE_MODEL:-claude-sonnet-4-20250514}
    volumes:
      - runs:/app/runs
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:5001/api/health > /dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 15s

volumes:
  runs:

